export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const GET_ITEM = 'GET_ITEM';
export const FAILED_ITEMS = 'FAILED_ITEMS';
export const FAILED_ITEM = "FAILED_ITEM"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOAD_NEXT = 'LOAD_NEXT'

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const FAILED_CATEGORIES = 'FAILED_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';

export const GET_PRICES = 'GET_PRICES';
export const FAILED_PRICES = 'FAILED_PRICES';
export const PRICES_LOADING ="PRICES_LOADING";

export const GET_RANDOM = 'GET_RANDOM';
export const REGISTER_SUCCES = 'REGISTER_SUCCES'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const NOT_LOGGEDIN = 'NOT_LOGGEDIN';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';
export const LOGIN_TOKEN = 'LOGIN_TOKEN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_ERRORS = 'LOADING_ERRORS'
export const REQUESTS = 'REQUESTS';

export const GET_RESERVATIONS = 'GET_RESERVATIONS'
export const ADD_RESERVATION = 'ADD_RESERVATION'
export const GET_PAST_RESERVATIONS ='GET_PAST_RESERVATIONS'
export const GET_FUTURE_RESERVATIONS = 'GET_FUTURE_RESERVATIONS'
export const RESERVATIONS_LOADING = 'RESERVATIONS_LOADING'
export const GET_RESERVATION = 'GET_RESERVATION'
export const FAILED_RESERVATIONS = 'FAILED_RESERVATIONS'
export const GET_TABLERESERVATIONS ='GET_TABLERESERVATIONS'
export const GET_WEEKLYRESERVATIONS ='GET_WEEKLYRESERVATIONS'
export const DELETE_RESERVATION = 'DELETE_RESERVATION'
export const RESERVATION_CLEAR_DELETE_SUCCES = 'RESERVATION_CLEAR_DELETE_SUCCES'

export const ADD_COMMENT = 'ADD_COMMENT'
export const GET_COMMENTS = 'GET_COMMENTS'
export const COMMENTS_LOADING = 'COMMENTS_LOADING'

export const ADD_FAVORITE= 'ADD_FAVORITE'
export const GET_FAVORITES = 'GET_FAVORITES'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'
export const GET_USER_FAVORITES = 'GET_USER_FAVORITES'
export const FAILED_FAVORITES = 'FAILED_FAVORITES'
export const FAVORITES_LOADING = 'FAVORITES_LOADING'
export const GET_USER_ALLFAVORITES = 'GET_USER_ALLFAVORITES'

export const GET_RATINGS = 'GET_RATINGS'
export const GET_RATING = 'GET_RATING'
export const ADD_RATING = 'ADD_RATING'
export const RATINGS_LOADING = 'RATINGS_LOADING'
export const FAILED_RATINGS = 'FAILED_RATINGS'
export const DELETE_RATING = 'DELETE_RATING' 

export const GET_PAYMENTS = "GET_PAYMENTS"
export const FAILED_PAYMENTS = "FAILED_PAYMENTS"
export const PAYMENTS_LOADING = 'PAYMENTS_LOADING'

export const GET_FACILITIES = "GET_FACILITIES"
export const FAILED_FACILITIES = "FAILED_FACILITIES"
export const FACILITIES_LOADING = 'FACILITIES_LOADING'

export const GET_PERSONS = "GET_PERSONS"
export const FAILED_PERSONS = "FAILED_PERSONS"
export const PERSONS_LOADING = "PERSONS_LOADING"

export const GET_TABLES = "GET_TABLES"
export const FAILED_TABLES = "FAILED_TABLES"
export const TABLES_LOADING = "TABLES_LOADING"

export const GET_EXTRAS = "GET_EXTRAS"
export const FAILED_EXTRAS = "FAILED_EXTRAS"
export const EXTRAS_LOADING = "EXTRAS_LOADING"

export const GET_ROOMS = "GET_ROOMS"
export const GET_ROOM = "GET_ROOM"
export const FAILED_ROOMS = "FAILED_ROOMS"
export const ROOMS_LOADING = "ROOMS_LOADING"
export const ADD_ROOM = "ADD_ROOM"

export const GET_LAYOUTS = "GET_LAYOUTS"
export const FAILED_LAYOUTS = "FAILED_LAYOUTS"
export const LAYOUTS_LOADING = "LAYOUTS_LOADING"
export const GET_LAYOUT = 'GET_LAYOUT'
export const ADD_LAYOUT = 'ADD_LAYOUT'
export const FORGET_LAYOUT = "FORGET_LAYOUT"
// DASHBOARD ACTIONS
export const GET_DAILY_RESERVATIONS = "GET_DAILY_RESERVATIONS"
export const GET_WEEKLY_RESERVATIONS = "GET_WEEKLY_RESERVATIONS"
export const GET_MONTHLY_RESERVATIONS = "GET_MONTHLY_RESERVATIONS"
export const GET_LAYOUTSDASHBOARD = "GET_LAYOUTSDASHBOARD"

export const DELETE_LAYOUT = "DELETE_LAYOUT"
export const UPDATE_LAYOUT = 'UPDATE_LAYOUT'

export const DELETE_ROOM = "DELETE_ROOM"
export const REMOVE_ROOM = "REMOVE_ROOM"
export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT"
export const GET_ROOMDASHBOARD = "GET_ROOMDASHBOARD"
export const UPDATE_ROOMDASHBOARD = "UPDATE_ROOMDASHBOARD"
export const GET_RECENT_RESERVATIONS = "GET_RECENT_RESERVATIONS"
export const DASHBOARD_LOADING = "DASHBOARD_LOADING"
export const FAILED_DASHBOARD = "FAILED_DASHBOARD"
export const GET_PLATTEGROND = "GET_PLATTEGROND"
export const MAKE_ROOM_UNACTIVE = 'MAKE_ROOM_UNACTIVE'
export const MAKE_ROOM_ACTIVE = 'MAKE_ROOM_ACTIVE'
export const RESET_SERVERRESPONSE = 'RESET_SERVERRESPONSE' 
export const GET_ACTIVEROOMS = 'GET_ACTIVEROOMS'
export const UPLOADPRIMARYIMG = 'UPLOADPRIMARYIMG'
export const UPLOADRESTAURANTIMAGES = "UPLOADRESTAURANTIMAGES"
export const GET_RESTAURANT = "GET_RESTAURANT"
export const DELETERESTAURANTIMAGE = "DELETERESTAURANTIMAGE"
export const GET_RECENT_COMMENTS = "GET_RECENT_COMMENTS"
export const LOADING_NEWDATA = "LOADING_NEWDATA"
export const UPLOADRESTAURANTMENUS = "UPLOADRESTAURANTMENUS"
export const IMAGES_LOADING = "IMAGES_LOADING"
export const DELETERESTAURANTMENUIMAGE = "DELETERESTAURANTMENUIMAGE" 
export const DELETERESTAURANTCAROUSELIMAGE = "DELETERESTAURANTCAROUSELIMAGE"
export const RESTAURANT_UPDATING = "RESTAURANT_UPDATING"
export const NOTUPDATED = "NOTUPDATED"